// Complete list of all 114 surahs with Arabic names and transliterations
export interface SurahInfo {
  id: number;
  nameArabic: string;
  nameEnglish: string;
  transliteration: string;
}

export const ALL_SURAHS: SurahInfo[] = [
  { id: 1, nameArabic: 'الفاتحة', nameEnglish: 'The Opening', transliteration: 'Al-Fatihah' },
  { id: 2, nameArabic: 'البقرة', nameEnglish: 'The Cow', transliteration: 'Al-Baqarah' },
  { id: 3, nameArabic: 'آل عمران', nameEnglish: 'Family of Imran', transliteration: 'Ali \'Imran' },
  { id: 4, nameArabic: 'النساء', nameEnglish: 'The Women', transliteration: 'An-Nisa' },
  { id: 5, nameArabic: 'المائدة', nameEnglish: 'The Table Spread', transliteration: 'Al-Ma\'idah' },
  { id: 6, nameArabic: 'الأنعام', nameEnglish: 'The Cattle', transliteration: 'Al-An\'am' },
  { id: 7, nameArabic: 'الأعراف', nameEnglish: 'The Heights', transliteration: 'Al-A\'raf' },
  { id: 8, nameArabic: 'الأنفال', nameEnglish: 'The Spoils of War', transliteration: 'Al-Anfal' },
  { id: 9, nameArabic: 'التوبة', nameEnglish: 'The Repentance', transliteration: 'At-Tawbah' },
  { id: 10, nameArabic: 'يونس', nameEnglish: 'Jonah', transliteration: 'Yunus' },
  { id: 11, nameArabic: 'هود', nameEnglish: 'Hud', transliteration: 'Hud' },
  { id: 12, nameArabic: 'يوسف', nameEnglish: 'Joseph', transliteration: 'Yusuf' },
  { id: 13, nameArabic: 'الرعد', nameEnglish: 'The Thunder', transliteration: 'Ar-Ra\'d' },
  { id: 14, nameArabic: 'إبراهيم', nameEnglish: 'Abraham', transliteration: 'Ibrahim' },
  { id: 15, nameArabic: 'الحجر', nameEnglish: 'The Rocky Tract', transliteration: 'Al-Hijr' },
  { id: 16, nameArabic: 'النحل', nameEnglish: 'The Bee', transliteration: 'An-Nahl' },
  { id: 17, nameArabic: 'الإسراء', nameEnglish: 'The Night Journey', transliteration: 'Al-Isra' },
  { id: 18, nameArabic: 'الكهف', nameEnglish: 'The Cave', transliteration: 'Al-Kahf' },
  { id: 19, nameArabic: 'مريم', nameEnglish: 'Mary', transliteration: 'Maryam' },
  { id: 20, nameArabic: 'طه', nameEnglish: 'Ta-Ha', transliteration: 'Ta-Ha' },
  { id: 21, nameArabic: 'الأنبياء', nameEnglish: 'The Prophets', transliteration: 'Al-Anbya' },
  { id: 22, nameArabic: 'الحج', nameEnglish: 'The Pilgrimage', transliteration: 'Al-Hajj' },
  { id: 23, nameArabic: 'المؤمنون', nameEnglish: 'The Believers', transliteration: 'Al-Mu\'minun' },
  { id: 24, nameArabic: 'النور', nameEnglish: 'The Light', transliteration: 'An-Nur' },
  { id: 25, nameArabic: 'الفرقان', nameEnglish: 'The Criterion', transliteration: 'Al-Furqan' },
  { id: 26, nameArabic: 'الشعراء', nameEnglish: 'The Poets', transliteration: 'Ash-Shu\'ara' },
  { id: 27, nameArabic: 'النمل', nameEnglish: 'The Ant', transliteration: 'An-Naml' },
  { id: 28, nameArabic: 'القصص', nameEnglish: 'The Stories', transliteration: 'Al-Qasas' },
  { id: 29, nameArabic: 'العنكبوت', nameEnglish: 'The Spider', transliteration: 'Al-\'Ankabut' },
  { id: 30, nameArabic: 'الروم', nameEnglish: 'The Romans', transliteration: 'Ar-Rum' },
  { id: 31, nameArabic: 'لقمان', nameEnglish: 'Luqman', transliteration: 'Luqman' },
  { id: 32, nameArabic: 'السجدة', nameEnglish: 'The Prostration', transliteration: 'As-Sajdah' },
  { id: 33, nameArabic: 'الأحزاب', nameEnglish: 'The Combined Forces', transliteration: 'Al-Ahzab' },
  { id: 34, nameArabic: 'سبأ', nameEnglish: 'Sheba', transliteration: 'Saba' },
  { id: 35, nameArabic: 'فاطر', nameEnglish: 'Originator', transliteration: 'Fatir' },
  { id: 36, nameArabic: 'يس', nameEnglish: 'Ya Sin', transliteration: 'Ya-Sin' },
  { id: 37, nameArabic: 'الصافات', nameEnglish: 'Those who set the Ranks', transliteration: 'As-Saffat' },
  { id: 38, nameArabic: 'ص', nameEnglish: 'The Letter "Saad"', transliteration: 'Sad' },
  { id: 39, nameArabic: 'الزمر', nameEnglish: 'The Troops', transliteration: 'Az-Zumar' },
  { id: 40, nameArabic: 'غافر', nameEnglish: 'The Forgiver', transliteration: 'Ghafir' },
  { id: 41, nameArabic: 'فصلت', nameEnglish: 'Explained in Detail', transliteration: 'Fussilat' },
  { id: 42, nameArabic: 'الشورى', nameEnglish: 'The Consultation', transliteration: 'Ash-Shuraa' },
  { id: 43, nameArabic: 'الزخرف', nameEnglish: 'The Ornaments of Gold', transliteration: 'Az-Zukhruf' },
  { id: 44, nameArabic: 'الدخان', nameEnglish: 'The Smoke', transliteration: 'Ad-Dukhan' },
  { id: 45, nameArabic: 'الجاثية', nameEnglish: 'The Crouching', transliteration: 'Al-Jathiyah' },
  { id: 46, nameArabic: 'الأحقاف', nameEnglish: 'The Wind-Curved Sandhills', transliteration: 'Al-Ahqaf' },
  { id: 47, nameArabic: 'محمد', nameEnglish: 'Muhammad', transliteration: 'Muhammad' },
  { id: 48, nameArabic: 'الفتح', nameEnglish: 'The Victory', transliteration: 'Al-Fath' },
  { id: 49, nameArabic: 'الحجرات', nameEnglish: 'The Rooms', transliteration: 'Al-Hujurat' },
  { id: 50, nameArabic: 'ق', nameEnglish: 'The Letter "Qaf"', transliteration: 'Qaf' },
  { id: 51, nameArabic: 'الذاريات', nameEnglish: 'The Winnowing Winds', transliteration: 'Adh-Dhariyat' },
  { id: 52, nameArabic: 'الطور', nameEnglish: 'The Mount', transliteration: 'At-Tur' },
  { id: 53, nameArabic: 'النجم', nameEnglish: 'The Star', transliteration: 'An-Najm' },
  { id: 54, nameArabic: 'القمر', nameEnglish: 'The Moon', transliteration: 'Al-Qamar' },
  { id: 55, nameArabic: 'الرحمن', nameEnglish: 'The Beneficent', transliteration: 'Ar-Rahman' },
  { id: 56, nameArabic: 'الواقعة', nameEnglish: 'The Inevitable', transliteration: 'Al-Waqi\'ah' },
  { id: 57, nameArabic: 'الحديد', nameEnglish: 'The Iron', transliteration: 'Al-Hadid' },
  { id: 58, nameArabic: 'المجادلة', nameEnglish: 'The Pleading Woman', transliteration: 'Al-Mujadila' },
  { id: 59, nameArabic: 'الحشر', nameEnglish: 'The Exile', transliteration: 'Al-Hashr' },
  { id: 60, nameArabic: 'الممتحنة', nameEnglish: 'She that is to be examined', transliteration: 'Al-Mumtahanah' },
  { id: 61, nameArabic: 'الصف', nameEnglish: 'The Ranks', transliteration: 'As-Saf' },
  { id: 62, nameArabic: 'الجمعة', nameEnglish: 'Friday', transliteration: 'Al-Jumu\'ah' },
  { id: 63, nameArabic: 'المنافقون', nameEnglish: 'The Hypocrites', transliteration: 'Al-Munafiqun' },
  { id: 64, nameArabic: 'التغابن', nameEnglish: 'The Mutual Disillusion', transliteration: 'At-Taghabun' },
  { id: 65, nameArabic: 'الطلاق', nameEnglish: 'The Divorce', transliteration: 'At-Talaq' },
  { id: 66, nameArabic: 'التحريم', nameEnglish: 'The Prohibition', transliteration: 'At-Tahrim' },
  { id: 67, nameArabic: 'الملك', nameEnglish: 'The Sovereignty', transliteration: 'Al-Mulk' },
  { id: 68, nameArabic: 'القلم', nameEnglish: 'The Pen', transliteration: 'Al-Qalam' },
  { id: 69, nameArabic: 'الحاقة', nameEnglish: 'The Reality', transliteration: 'Al-Haqqah' },
  { id: 70, nameArabic: 'المعارج', nameEnglish: 'The Ascending Stairways', transliteration: 'Al-Ma\'arij' },
  { id: 71, nameArabic: 'نوح', nameEnglish: 'Noah', transliteration: 'Nuh' },
  { id: 72, nameArabic: 'الجن', nameEnglish: 'The Jinn', transliteration: 'Al-Jinn' },
  { id: 73, nameArabic: 'المزمل', nameEnglish: 'The Enshrouded One', transliteration: 'Al-Muzzammil' },
  { id: 74, nameArabic: 'المدثر', nameEnglish: 'The Cloaked One', transliteration: 'Al-Muddaththir' },
  { id: 75, nameArabic: 'القيامة', nameEnglish: 'The Resurrection', transliteration: 'Al-Qiyamah' },
  { id: 76, nameArabic: 'الإنسان', nameEnglish: 'The Man', transliteration: 'Al-Insan' },
  { id: 77, nameArabic: 'المرسلات', nameEnglish: 'The Emissaries', transliteration: 'Al-Mursalat' },
  { id: 78, nameArabic: 'النبأ', nameEnglish: 'The Tidings', transliteration: 'An-Naba' },
  { id: 79, nameArabic: 'النازعات', nameEnglish: 'Those who drag forth', transliteration: 'An-Nazi\'at' },
  { id: 80, nameArabic: 'عبس', nameEnglish: 'He Frowned', transliteration: '\'Abasa' },
  { id: 81, nameArabic: 'التكوير', nameEnglish: 'The Overthrowing', transliteration: 'At-Takwir' },
  { id: 82, nameArabic: 'الانفطار', nameEnglish: 'The Cleaving', transliteration: 'Al-Infitar' },
  { id: 83, nameArabic: 'المطففين', nameEnglish: 'The Defrauding', transliteration: 'Al-Mutaffifin' },
  { id: 84, nameArabic: 'الانشقاق', nameEnglish: 'The Sundering', transliteration: 'Al-Inshiqaq' },
  { id: 85, nameArabic: 'البروج', nameEnglish: 'The Mansions of the Stars', transliteration: 'Al-Buruj' },
  { id: 86, nameArabic: 'الطارق', nameEnglish: 'The Nightcommer', transliteration: 'At-Tariq' },
  { id: 87, nameArabic: 'الأعلى', nameEnglish: 'The Most High', transliteration: 'Al-A\'la' },
  { id: 88, nameArabic: 'الغاشية', nameEnglish: 'The Overwhelming', transliteration: 'Al-Ghashiyah' },
  { id: 89, nameArabic: 'الفجر', nameEnglish: 'The Dawn', transliteration: 'Al-Fajr' },
  { id: 90, nameArabic: 'البلد', nameEnglish: 'The City', transliteration: 'Al-Balad' },
  { id: 91, nameArabic: 'الشمس', nameEnglish: 'The Sun', transliteration: 'Ash-Shams' },
  { id: 92, nameArabic: 'الليل', nameEnglish: 'The Night', transliteration: 'Al-Layl' },
  { id: 93, nameArabic: 'الضحى', nameEnglish: 'The Morning Hours', transliteration: 'Ad-Duhaa' },
  { id: 94, nameArabic: 'الشرح', nameEnglish: 'The Relief', transliteration: 'Ash-Sharh' },
  { id: 95, nameArabic: 'التين', nameEnglish: 'The Fig', transliteration: 'At-Tin' },
  { id: 96, nameArabic: 'العلق', nameEnglish: 'The Clot', transliteration: 'Al-\'Alaq' },
  { id: 97, nameArabic: 'القدر', nameEnglish: 'The Power', transliteration: 'Al-Qadr' },
  { id: 98, nameArabic: 'البينة', nameEnglish: 'The Clear Proof', transliteration: 'Al-Bayyinah' },
  { id: 99, nameArabic: 'الزلزلة', nameEnglish: 'The Earthquake', transliteration: 'Az-Zalzalah' },
  { id: 100, nameArabic: 'العاديات', nameEnglish: 'The Courser', transliteration: 'Al-\'Adiyat' },
  { id: 101, nameArabic: 'القارعة', nameEnglish: 'The Calamity', transliteration: 'Al-Qari\'ah' },
  { id: 102, nameArabic: 'التكاثر', nameEnglish: 'The Rivalry in world increase', transliteration: 'At-Takathur' },
  { id: 103, nameArabic: 'العصر', nameEnglish: 'The Declining Day', transliteration: 'Al-\'Asr' },
  { id: 104, nameArabic: 'الهمزة', nameEnglish: 'The Traducer', transliteration: 'Al-Humazah' },
  { id: 105, nameArabic: 'الفيل', nameEnglish: 'The Elephant', transliteration: 'Al-Fil' },
  { id: 106, nameArabic: 'قريش', nameEnglish: 'Quraysh', transliteration: 'Quraysh' },
  { id: 107, nameArabic: 'الماعون', nameEnglish: 'The Small kindnesses', transliteration: 'Al-Ma\'un' },
  { id: 108, nameArabic: 'الكوثر', nameEnglish: 'The Abundance', transliteration: 'Al-Kawthar' },
  { id: 109, nameArabic: 'الكافرون', nameEnglish: 'The Disbelievers', transliteration: 'Al-Kafirun' },
  { id: 110, nameArabic: 'النصر', nameEnglish: 'The Divine Support', transliteration: 'An-Nasr' },
  { id: 111, nameArabic: 'المسد', nameEnglish: 'The Palm Fiber', transliteration: 'Al-Masad' },
  { id: 112, nameArabic: 'الإخلاص', nameEnglish: 'The Sincerity', transliteration: 'Al-Ikhlas' },
  { id: 113, nameArabic: 'الفلق', nameEnglish: 'The Daybreak', transliteration: 'Al-Falaq' },
  { id: 114, nameArabic: 'الناس', nameEnglish: 'Mankind', transliteration: 'An-Nas' },
];

export const JUZ_AMMA_START = 78; // Surahs 78-114
export const FIRST_10_SURAHS = 10;
